### ISSUE TITLE
Absenden bei Behinderung nicht möglich

### ISSUE THREAD

**Issue by SiSoKiB** [digital-bauhaus/Ferienpass#13]
Wenn man die Daten für ein behindertes Kind eingibt, wird das Dokument nicht abgeschickt. Ist der Haken entfernt, geht es.

**Comment by mcguenther** [comment]
Dokument wird abgeschickt, Server antwortet aber mit Fehler 500.

Log-Auszug vom Server
```
2019-05-03 16:45:37.007 ERROR 11212 --- [nio-8088-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at de.bauhaus.digital.transformation.AnmeldungToAdmin.mappeBegleitpersonenDaten(AnmeldungToAdmin.java:78) ~[classes/:na]
	at de.bauhaus.digital.transformation.AnmeldungToAdmin.mappeDatenZuBehinderungen(AnmeldungToAdmin.java:56) ~[classes/:na]
...

```
Der Server bekommt keinen Fehler, wenn man ein Häkchen setzt bei:
"Mein Kind hat im Schulalltag eine Schulbegleitung und benötigt auch während der Ferienfreizeit eine Begleitperson"
