### ISSUE TITLE
"eMail mit Zahlungsaufforderung" im Geschafft-Dialog der Registrierung

### ISSUE THREAD

**Issue by jonashackt** [digital-bauhaus/Ferienpass#57]
Bisher wird keine Mail verschickt - sollen wir das noch bauen oder reicht eine einfache Aufforderung: "Bitte kommen Sie zur Bezahlung ins Kinderbüro Weimar" @SiSoKiB ?!

**Comment by jonashackt** [comment]
Siehe auch #2

**Comment by jonashackt** [comment]
Hiermit könnten wir Mails verschicken: https://devcenter.heroku.com/articles/smtp

**Comment by jonashackt** [comment]
Weil alle Dienste, die hier https://stackoverflow.com/questions/12750864/temporary-e-mail-accounts-for-integration-tests beschrieben wurden, nicht wirklich funktionieren (oder nicht kostenlos sind), verwenden wir nun erstmal meinen persönlichen googlemail-account mit der `username+testaccount@gmail.com` notation.

**Comment by jonashackt** [comment]
Getting 

```
2019-06-12T10:44:45.298605+00:00 app[web.1]: java.io.FileNotFoundException: class path resource [mail/mailtext.txt] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/app/backend/target/backend-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/mail/mailtext.txt
2019-06-12T10:44:45.298607+00:00 app[web.1]: at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-06-12T10:44:45.298609+00:00 app[web.1]: at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:154) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-06-12T10:44:45.298610+00:00 app[web.1]: at de.bauhaus.digital.controller.BackendController.readMailText(BackendController.java:443) ~[classes!/:0.0.1-SNAPSHOT]
2019-06-12T10:44:45.298611+00:00 app[web.1]: at de.bauhaus.digital.controller.BackendController.sendMail(BackendController.java:426) ~[classes!/:0.0.1-SNAPSHOT]
2019-06-12T10:44:45.298613+00:00 app[web.1]: at de.bauhaus.digital.controller.BackendController.registerNewTeilnehmer(BackendController.java:399) ~[classes!/:0.0.1-SNAPSHOT]
2019-06-12T10:44:45.298615+00:00 app[web.1]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212-heroku]
2019-06-12T10:44:45.298617+00:00 app[web.1]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212-heroku]
2019-06-12T10:44:45.298618+00:00 app[web.1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212-heroku]
2019-06-12T10:44:45.298620+00:00 app[web.1]: at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212-heroku]
2019-06-12T10:44:45.298621+00:00 app[web.1]: at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-06-12T10:44:45.298623+00:00 app[web.1]: at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-06-12T10:44:45.298626+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-06-12T10:44:45.298627+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-06-12T10:44:45.298628+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-06-12T10:44:45.298630+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-06-12T10:44:45.298631+00:00 app[web.1]: at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-06-12T10:44:45.298632+00:00 app[web.1]: at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
```

only on the server :( *** I hate filereading with Java 😲
